<a href="https://colab.research.google.com/github/Jinwooseol/Numpy-and-Pandas/blob/main/20220316_Numpy_1darray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

np.set_printoptions(precision=3)

In [ ]:
np.version.version

'1.21.5'

#Difference between Numpy and Python

#Numpy
- Array
- '$~$,$~$' doesn't exist in Numpy's array
- All of elements must be the same type (a.i. int, floor, char ...)  
  $→$If, there exist various types in array, then change the types to one uniformed type
- Reallocate the new array
- View (Referencing)


#Python
- List
- Comma (,) exist in Python's list
- Allow various types of elements in one list
- Expand the size of list
- Copy and Paste

In [ ]:
list1 = [1,2,3,4,5]
print(list1)

a1 = np.array([1,2,3,4,5])
list1 = [1,2,3,4,5]



In [ ]:
def print_info(obj):
  print('type: ', type(obj))
  print('print: {}'.format(obj))

  # 1D array
  print('ndim: ', obj.ndim)
  print('shape: ', obj.shape)
  print('size: ', obj.size)
  print('dtype: ', obj.dtype) # dtype: Data type
  print('itemsize: ', obj.itemsize) # itemsize: Number of bytes that one of element occupied
  print('data: ', obj.data)  # data: Address of array

  #print('-'*20)

  #for i in a1:
    #print(i)

  #print('-'*20)

  #for i, j in enumerate(a1):
    #print(i, j)

In [ ]:
print_info(a1)

type: <class 'numpy.ndarray'>
print: [1 2 3 4 5]
ndim:  1
shape:  (5,)
size:  5
dtype:  int64
itemsize:  8
data:  <memory at 0x7f97305b37a0>


In [ ]:
py_list = [1,2,3,'a','b','c']
print(py_list)

a2 = np.array(py_list)
print_info(a2)

# dtype: U21: Unicode, 21 buffers used
# change the element's type from int to char

[1, 2, 3, 'a', 'b', 'c']
type: <class 'numpy.ndarray'>
print: ['1' '2' '3' 'a' 'b' 'c']
ndim:  1
shape:  (6,)
size:  6
dtype:  <U21
itemsize:  84
data:  <memory at 0x7f97307d07a0>


In [ ]:
# Odd numbers btw 10 and 50
a3 = np.array([i for i in range(11, 50, 2)])
print_info(a3)

a4 = np.array([i for i in range(11, 50, 2)], dtype=np.float64)
print_info(a4)
# 11. -> '.' means that float64 (real Number)


type: <class 'numpy.ndarray'>
print: [11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49]
ndim:  1
shape:  (20,)
size:  20
dtype:  int64
itemsize:  8
data:  <memory at 0x7f97305b3bb0>
type: <class 'numpy.ndarray'>
print: [11. 13. 15. 17. 19. 21. 23. 25. 27. 29. 31. 33. 35. 37. 39. 41. 43. 45.
 47. 49.]
ndim:  1
shape:  (20,)
size:  20
dtype:  float64
itemsize:  8
data:  <memory at 0x7f97305b3c80>


np.arange(**start**, **stop**, **step**): Possible of using *Real number*

In [ ]:
list2 = [x for x in range(5, 20, 2)]
print(list2)

a5 = np.arange(5.0, 10.0, 0.2)
print_info(a5)

[5, 7, 9, 11, 13, 15, 17, 19]
type: <class 'numpy.ndarray'>
print: [5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.  7.2 7.4 7.6 7.8 8.  8.2 8.4
 8.6 8.8 9.  9.2 9.4 9.6 9.8]
ndim:  1
shape:  (25,)
size:  25
dtype:  float64
itemsize:  8
data:  <memory at 0x7f97305b3d50>


In [ ]:
# From -3.14 to 3.14, step is 0.25
a6 = np.arange(-3.14, 3.14, 0.25)
print_info(a6)

type: <class 'numpy.ndarray'>
print: [-3.14 -2.89 -2.64 -2.39 -2.14 -1.89 -1.64 -1.39 -1.14 -0.89 -0.64 -0.39
 -0.14  0.11  0.36  0.61  0.86  1.11  1.36  1.61  1.86  2.11  2.36  2.61
  2.86  3.11]
ndim:  1
shape:  (26,)
size:  26
dtype:  float64
itemsize:  8
data:  <memory at 0x7f97305b3ae0>


np.linspace(**start**, **end**, **number of elements**)  
- Elements that have **same interval**

In [ ]:
a7 = np.linspace(10, 100, 5)
print_info(a7)

type: <class 'numpy.ndarray'>
print: [ 10.   32.5  55.   77.5 100. ]
ndim:  1
shape:  (5,)
size:  5
dtype:  float64
itemsize:  8
data:  <memory at 0x7f97305b3a10>


In [ ]:
# From -1.25 to 1.25, # of elements is 50
a8 = np.linspace(-1.25, 1.25, 50)
print_info(a8)

type:  <class 'numpy.ndarray'>
print: [-1.25       -1.19897959 -1.14795918 -1.09693878 -1.04591837 -0.99489796
 -0.94387755 -0.89285714 -0.84183673 -0.79081633 -0.73979592 -0.68877551
 -0.6377551  -0.58673469 -0.53571429 -0.48469388 -0.43367347 -0.38265306
 -0.33163265 -0.28061224 -0.22959184 -0.17857143 -0.12755102 -0.07653061
 -0.0255102   0.0255102   0.07653061  0.12755102  0.17857143  0.22959184
  0.28061224  0.33163265  0.38265306  0.43367347  0.48469388  0.53571429
  0.58673469  0.6377551   0.68877551  0.73979592  0.79081633  0.84183673
  0.89285714  0.94387755  0.99489796  1.04591837  1.09693878  1.14795918
  1.19897959  1.25      ]
ndim:  1
shape:  (50,)
size:  50
dtype:  float64
itemsize:  8
data:  <memory at 0x7f97303676d0>


In [ ]:
a9 = np.zeros(10)
print_info(a9)

print('\n')
list4 = [0]*10
print('Python list:', list4)
print('Type: ', type(list4[0]))

type:  <class 'numpy.ndarray'>
print: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
ndim:  1
shape:  (10,)
size:  10
dtype:  float64
itemsize:  8
data:  <memory at 0x7f97303677a0>


Python list: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Type:  <class 'int'>


In [ ]:
a10 = np.ones(10)
print(a10)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
a11 = np.empty(20)
print(a11)

# Not defined elements (occupied elements in memory)

[11. 13. 15. 17. 19. 21. 23. 25. 27. 29. 31. 33. 35. 37. 39. 41. 43. 45.
 47. 49.]


In [ ]:
list5 = [x for x in range(5, 15, 3)]
print(list5)
print('\n')

a12 = np.zeros(len(list5))
print_info(a12)
print('\n')

a13 = np.zeros_like(list5)
print_info(a13)
print('\n')

list6 = [1.1, 1.2, 1.3, 1.4]
a14 = np.ones_like(list6)
print(a14)

[5, 8, 11, 14]


type:  <class 'numpy.ndarray'>
print: [0. 0. 0. 0.]
ndim:  1
shape:  (4,)
size:  4
dtype:  float64
itemsize:  8
data:  <memory at 0x7f9730367ae0>


type:  <class 'numpy.ndarray'>
print: [0 0 0 0]
ndim:  1
shape:  (4,)
size:  4
dtype:  int64
itemsize:  8
data:  <memory at 0x7f9730367ef0>


[1. 1. 1. 1.]


In [ ]:
a15 = np.empty_like(list6)
print(a15)

[0. 0. 0. 0.]


np.fromfunction(**function**, **shape**)  
- **function** adapted array


In [ ]:
def f1(x):
  return 5*x

list7 = [f1(x) for x in range(1, 10, 2)]
print(list7)

a16 = np.fromfunction(f1, (10,), dtype=int)
print(a16)

[5, 15, 25, 35, 45]
[ 0  5 10 15 20 25 30 35 40 45]


# dtype
- **np.int64**: signed int (32 bits)
- **np.uint64**: unsigned int (64 bits)
- **np.bool8 / np.bool_** 
- **np.float64**
- **np.unicode_** 

Reference: https://numpy.org/doc/stable/reference/arrays.dtypes.html

In [ ]:
import math

list1 = [x for x in range(-5, 5)]
#print(math.sin(10))
print(np.sin(list1))
print('\n')

a1 = np.arange(-5, 5)
print(np.sin(a1))



[ 0.95892427  0.7568025  -0.14112001 -0.90929743 -0.84147098  0.
  0.84147098  0.90929743  0.14112001 -0.7568025 ]


[ 0.95892427  0.7568025  -0.14112001 -0.90929743 -0.84147098  0.
  0.84147098  0.90929743  0.14112001 -0.7568025 ]


#Indexing


In [ ]:
import numpy as np

a1 = np.arange(1, 10 , 2)
print(a1)
print(a1[3])
print(a1[1:3])
print(a1[:4:2])

[1 3 5 7 9]
7
[3 5]
[1 5]


In [ ]:
a1 = np.arange(100, 200, 2)
print(a1)
print(a1[15]) # Normal indexing
print(a1[:3])
print(a1[5:10:2])

a1[5:10:2] = 0  
print(a1)

[100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158 160 162 164 166 168 170
 172 174 176 178 180 182 184 186 188 190 192 194 196 198]
130
[100 102 104]
[110 114 118]
[100 102 104 106 108   0 112   0 116   0 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158 160 162 164 166 168 170
 172 174 176 178 180 182 184 186 188 190 192 194 196 198]


In [ ]:
# From 75 to 83, step = 0.3, type = ndarray, even indexed values = 0
a2 = np.arange(75, 83, 0.3)
a2[::2] = 0   # Same with a2[0:83:2]
print(a2)

[ 0.  75.3  0.  75.9  0.  76.5  0.  77.1  0.  77.7  0.  78.3  0.  78.9
  0.  79.5  0.  80.1  0.  80.7  0.  81.3  0.  81.9  0.  82.5  0. ]


#Indexing using list elements

In [ ]:
a3 = np.arange(30., 40.)
index_list = np.arange(0, 10, 3)
print(a3)
print(index_list)
print(a3[index_list])

a3[index_list] = 100
print(a3)

[30. 31. 32. 33. 34. 35. 36. 37. 38. 39.]
[0 3 6 9]
[30. 33. 36. 39.]
[100.  31.  32. 100.  34.  35. 100.  37.  38. 100.]


In [ ]:
# From -3.14 to 3.14, # of elements = 100, type = ndarray, 7 multiplies with 0 indexed values = 0
a4 = np.linspace(-3.14, 3.14, 100)
a4[::7] = 0
print_info(a4)

type:  <class 'numpy.ndarray'>
print: [ 0.    -3.077 -3.013 -2.95  -2.886 -2.823 -2.759  0.    -2.633 -2.569
 -2.506 -2.442 -2.379 -2.315  0.    -2.188 -2.125 -2.062 -1.998 -1.935
 -1.871  0.    -1.744 -1.681 -1.618 -1.554 -1.491 -1.427  0.    -1.3
 -1.237 -1.174 -1.11  -1.047 -0.983  0.    -0.856 -0.793 -0.729 -0.666
 -0.603 -0.539  0.    -0.412 -0.349 -0.285 -0.222 -0.159 -0.095  0.
  0.032  0.095  0.159  0.222  0.285  0.349  0.     0.476  0.539  0.603
  0.666  0.729  0.793  0.     0.92   0.983  1.047  1.11   1.174  1.237
  0.     1.364  1.427  1.491  1.554  1.618  1.681  0.     1.808  1.871
  1.935  1.998  2.062  2.125  0.     2.252  2.315  2.379  2.442  2.506
  2.569  0.     2.696  2.759  2.823  2.886  2.95   3.013  0.     3.14 ]
ndim:  1
shape:  (100,)
size:  100
dtype:  float64
itemsize:  8
data:  <memory at 0x7f97302f0ef0>


#Indexing using bool type list
- array[**True or False**]

In [ ]:
a5 = np.arange(0., 10.)
index_list_a = [True]*5
index_list_b = [False]*5
index_list = index_list_a + index_list_b

print(a5)
print(index_list)
print(a5[index_list])

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[True, True, True, True, True, False, False, False, False, False]
[0. 1. 2. 3. 4.]


In [ ]:
index_list = (a5 % 2 == 0)
print(index_list)
print(a5[index_list])
print(a5[a5 % 2 == 0])
print(a5[a5 < 3])

[ True False  True False  True False  True False  True False]
[0. 2. 4. 6. 8.]
[0. 2. 4. 6. 8.]
[0. 1. 2.]


In [ ]:
list1 = [1,2,3,4,5]
list2 = list1[1:3]

print(list1)
print(list2)
list2[0] += 1

print(list1)
print(list2)


[1, 2, 3, 4, 5]
[2, 3]
[1, 2, 3, 4, 5]
[3, 3]


In [ ]:
a1 = np.array([1,2,3,4,5])
a2 = a1[1:3]  # Create view (Referencing)
print(a1)
print(a2)

a2[0] += 1
print(a1)
print(a2)

[1 2 3 4 5]
[2 3]
[1 3 3 4 5]
[3 3]


In [ ]:
a1 = np.array([1,2,3,4,5])
a2 = a1[1:3].copy() # Create new ndarray (copy and paste)
print(a1)
print(a2)

a2[0] += 1
print(a1)
print(a2)

[1 2 3 4 5]
[2 3]
[1 2 3 4 5]
[3 3]


# Basic Operations

In [ ]:
a1 = np.arange(0., 10.)
a2 = np.arange(20., 30.)
print(a1)
print(a2)
print(a1 + a2)
print(a1 - a2)
print(a1 * a2)
print(a1 / a2)
print(a1 % a2)
print(a1 // a2)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]
[20. 22. 24. 26. 28. 30. 32. 34. 36. 38.]
[-20. -20. -20. -20. -20. -20. -20. -20. -20. -20.]
[  0.  21.  44.  69.  96. 125. 156. 189. 224. 261.]
[0.    0.048 0.091 0.13  0.167 0.2   0.231 0.259 0.286 0.31 ]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# function = 5*x**2 + x, x btw -10, 10, step = 0.5, type = ndarray
# 5 multiplies indexed values print

def f1(x):
  return 5*(x**2) + x

a1 = f1(np.arange(-10, 10, 0.5))
print(a1[a1 % 5 == 0])

[490. 120.   0. 130.]
