<a href="https://colab.research.google.com/github/Jinwooseol/Numpy-and-Pandas/blob/main/2022_03_23_Universal_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Universal Functions
https://numpy.org/doc/stable/reference/ufuncs.html

In [ ]:
import numpy as np
from numpy import random
from numpy.random import default_rng

In [ ]:
def print_info(obj):
  print('type: ', type(obj))
  print('print: ')
  print(obj)

  print('ndim: ', obj.ndim)
  print('shape: ', obj.shape)
  print('size: ', obj.size)
  print('dtype: ', obj.dtype) # dtype: Data type
  print('itemsize: ', obj.itemsize) # itemsize: Number of bytes that one of element occupied
  print('data: {}'.format(obj.data))  # data: Address of array
  print('-'*20)


# Random number generator
- rng.integers(**low**, **high**, **shape**): Generate random integers between low and high
- rng.random(**shape**): Generate random real numbers


In [ ]:
rng = default_rng() # rng: random number generator
# rng = np.random.default_rng()
print(rng.integers(0, 10, (5, 5)))
print(rng.random((2, 5)))  # Random real number
print(np.random.rand(2, 5))

[[1 4 2 4 1]
 [0 2 5 3 0]
 [2 9 2 8 7]
 [8 8 1 7 6]
 [6 3 7 2 7]]
[[0.94683203 0.70969973 0.19330111 0.24636855 0.24748236]
 [0.15011569 0.47630242 0.82717609 0.37509522 0.54284113]]
[[0.21045938 0.41080038 0.50095843 0.52206189 0.35130032]
 [0.42926261 0.56309755 0.89318202 0.13060934 0.63213525]]


**np.random.shuffle**: In-place mix  
**np.random.permutation**: Create mixed new ndarray

In [ ]:
a1 = np.arange(10)
print(a1)

random.shuffle(a1) # In-place mix
print(a1)

a2 = np.arange(10)
print(a2)

a3 = random.permutation(a2)  # Create mixed new ndarray
print(a3)
print(a2)

[0 1 2 3 4 5 6 7 8 9]
[8 9 4 1 3 5 6 2 7 0]
[0 1 2 3 4 5 6 7 8 9]
[4 9 6 5 2 3 7 0 1 8]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
a1 = np.arange(-10, 10, 2)
np.random.shuffle(a1)
print(a1)

print(np.choose([1,3,5], a1)) # select element using index list a1[1], a1[3], a1[5]
print(np.take(a1, [1,3,5])) 


[  0   4  -6   2 -10  -8  -4   8   6  -2]
[ 4  2 -8]
[ 4  2 -8]


np.random.shuffle mix just one axis

In [ ]:
# Just shuffle axis 0

a2 = np.arange(-10, 10).reshape(4, -1)
print(a2)
np.random.shuffle(a2)
print(a2)

a3 = random.permutation(a2)
print(a3)

[[-10  -9  -8  -7  -6]
 [ -5  -4  -3  -2  -1]
 [  0   1   2   3   4]
 [  5   6   7   8   9]]
[[ -5  -4  -3  -2  -1]
 [  0   1   2   3   4]
 [  5   6   7   8   9]
 [-10  -9  -8  -7  -6]]
[[  0   1   2   3   4]
 [-10  -9  -8  -7  -6]
 [  5   6   7   8   9]
 [ -5  -4  -3  -2  -1]]


**np.choose(index_list, ndarray)**: Get elements in index_list (= axis 0)  
**np.take(ndarray, index_list)**: Get elements in index_list after flatten

In [ ]:
# Shuffle all

a2 = np.arange(-10, 10)
np.random.shuffle(a2)
a2 = a2.reshape(4, -1)
print(a2)

print(np.choose([3,2,1,0,2], a2)) # a2[3,0], [2,1] [1,2] [0,3] [2,4] Axis 0
print(np.take(a2, [3,2,1,0,2]))
print(np.take(a2, [11, 10, 5, 19, 6]))

[[ -1   4   3   8  -2]
 [ -3  -8 -10   5   1]
 [ -6   0   7  -5  -7]
 [ -4   9   2  -9   6]]
[ -4   0 -10   8  -7]
[ 8  3  4 -1  3]
[ 0 -6 -3  6 -8]


In [ ]:
a3 = a2.swapaxes(0, 1) # Swap axis 0 and axis 1

print(a2)
print(a2.shape)

print(a3)
print(a3.shape)

print(a2.transpose())
print(a2.transpose().shape)

[[ -1   4   3   8  -2]
 [ -3  -8 -10   5   1]
 [ -6   0   7  -5  -7]
 [ -4   9   2  -9   6]]
(4, 5)
[[ -1  -3  -6  -4]
 [  4  -8   0   9]
 [  3 -10   7   2]
 [  8   5  -5  -9]
 [ -2   1  -7   6]]
(5, 4)
[[ -1  -3  -6  -4]
 [  4  -8   0   9]
 [  3 -10   7   2]
 [  8   5  -5  -9]
 [ -2   1  -7   6]]
(5, 4)


In [ ]:
a3 = np.arange(-20, 20)
np.random.shuffle(a3)
a3 = a3.reshape(2,4,5)
print(a3)
print(a3.shape)
print('-'*20)

a4 = a3.swapaxes(0, 1)
print(a4)
print(a4.shape)
print('-'*20)

a5 = a3.swapaxes(0, 2)
print(a5)
print(a5.shape)
print('-'*20)

a6 = a3.swapaxes(1, 2)
print(a6)
print(a6.shape)
print('-'*20)

a7 = a3.transpose() # = a3.swapaxes(0, 2)
print(a7)
print(a7.shape)

[[[  1  -1 -18   2 -11]
  [ 10  -8 -13 -14   6]
  [  5 -15  17   9   8]
  [-12   7 -20  -2  15]]

 [[ -3   3  -9  13  11]
  [ -4   4 -10  -6  -5]
  [ 18  16 -19  -7  14]
  [  0  19 -16  12 -17]]]
(2, 4, 5)
--------------------
[[[  1  -1 -18   2 -11]
  [ -3   3  -9  13  11]]

 [[ 10  -8 -13 -14   6]
  [ -4   4 -10  -6  -5]]

 [[  5 -15  17   9   8]
  [ 18  16 -19  -7  14]]

 [[-12   7 -20  -2  15]
  [  0  19 -16  12 -17]]]
(4, 2, 5)
--------------------
[[[  1  -3]
  [ 10  -4]
  [  5  18]
  [-12   0]]

 [[ -1   3]
  [ -8   4]
  [-15  16]
  [  7  19]]

 [[-18  -9]
  [-13 -10]
  [ 17 -19]
  [-20 -16]]

 [[  2  13]
  [-14  -6]
  [  9  -7]
  [ -2  12]]

 [[-11  11]
  [  6  -5]
  [  8  14]
  [ 15 -17]]]
(5, 4, 2)
--------------------
[[[  1  10   5 -12]
  [ -1  -8 -15   7]
  [-18 -13  17 -20]
  [  2 -14   9  -2]
  [-11   6   8  15]]

 [[ -3  -4  18   0]
  [  3   4  16  19]
  [ -9 -10 -19 -16]
  [ 13  -6  -7  12]
  [ 11  -5  14 -17]]]
(2, 5, 4)
--------------------
[[[  1  -3]
  [ 10  -4]
  

# Set operation
- unique
- union1d
- intersect1d
- setdiff1d
- setxor1d

In [ ]:
a1 = np.random.default_rng().integers(0, 10, 10)
print(a1)

a2 = np.random.default_rng().integers(0, 20, 10)
print(a2)

x = np.unique(a1) # set element
print(x)

x = np.unique(a1, return_counts = True) # set element with count
print(x)

x = np.union1d(a1, a2) # set element   a1 or a2
print(x)

x = np.intersect1d(a1, a2) # set element a1 and a2
print(x)

x = np.setdiff1d(a1, a2) # set element a1 - a2
print(x)

x = np.setxor1d(a1, a2) # set element a1 xor a2
print(x)

[8 0 1 9 6 2 0 9 2 2]
[15 11 18  5 12  8 12 12 19 11]
[0 1 2 6 8 9]
(array([0, 1, 2, 6, 8, 9]), array([2, 1, 3, 1, 1, 2]))
[ 0  1  2  5  6  8  9 11 12 15 18 19]
[8]
[0 1 2 6 9]
[ 0  1  2  5  6  9 11 12 15 18 19]


# Universal functions
- **Parameter**: out, where

In [ ]:
a1 = np.arange(10)
a2 = np.arange(100, 110)
a3 = np.empty(10, dtype = int)
print(a1)
print(a2)
print(a1 + a2)
print(np.add(a1, a2, out = a3)) # a3 = a1 + a2
print(a3)

a3 = np.zeros(10)
print(np.add(a1, a2, out = a3, where = (a1 % 2 == 0))) # where: same with SQL

[0 1 2 3 4 5 6 7 8 9]
[100 101 102 103 104 105 106 107 108 109]
[100 102 104 106 108 110 112 114 116 118]
[100 102 104 106 108 110 112 114 116 118]
[100 102 104 106 108 110 112 114 116 118]
[100.   0. 104.   0. 108.   0. 112.   0. 116.   0.]


- **Method**: reduce, accumulate, reduceat

In [ ]:
a1 = np.arange(10).reshape(2, -1)
a2 = np.arange(100, 110).reshape(2,-1)

print(a1)
print(a2)
print('-'*25)

print(np.add.reduce(a1, axis = 0)) # == sum.(axis = 0)
print(np.add.accumulate(a1, axis = 0))
print('-'*25)

print(np.add.reduce(a1, axis = 1)) # == sum.(axis = 1)
print(np.add.accumulate(a1, axis = 1))
print('-'*25)

print(np.add.reduceat(a1, [1, 3], axis = 1)) # sum (1, 2), sum(3, 4)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[100 101 102 103 104]
 [105 106 107 108 109]]
-------------------------
[ 5  7  9 11 13]
[[ 0  1  2  3  4]
 [ 5  7  9 11 13]]
-------------------------
[10 35]
[[ 0  1  3  6 10]
 [ 5 11 18 26 35]]
-------------------------
[[ 3  7]
 [13 17]]


In [ ]:
a1 = np.arange(1, 25).reshape(2,3,4)
print(a1)
print('-'*25)
print(np.add.reduce(a1, axis=2))
print('-'*25)
print(np.add.reduceat(a1, [0, 2], axis = 2))

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
-------------------------
[[10 26 42]
 [58 74 90]]
-------------------------
[[[ 3  7]
  [11 15]
  [19 23]]

 [[27 31]
  [35 39]
  [43 47]]]


- **Method**: outer

In [ ]:
# a1 = np.arange(10)
# a2 = np.arange(100, 110)
# # print(a1)
# print(a2)
# print(np.add.outer(a1, a2)) # a1 -> row, a2 -> column / sum of row and column

a1 = np.arange(10).reshape(2, 5)
a2 = np.arange(20, 40, 4).reshape(-1, 5)
a3 = np.add.outer(a1, a2)
print(a1)
print('-'*20)
print(a2)
print('-'*20)
print(a3)
print(a3.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
--------------------
[[20 24 28 32 36]]
--------------------
[[[[20 24 28 32 36]]

  [[21 25 29 33 37]]

  [[22 26 30 34 38]]

  [[23 27 31 35 39]]

  [[24 28 32 36 40]]]


 [[[25 29 33 37 41]]

  [[26 30 34 38 42]]

  [[27 31 35 39 43]]

  [[28 32 36 40 44]]

  [[29 33 37 41 45]]]]
(2, 5, 1, 5)


**Method**: at

In [ ]:
a1 = np.arange(10)
print(a1)
np.add.at(a1, [0, 1], 100) # adapt function selectively index [0], [1]
print(a1)

[0 1 2 3 4 5 6 7 8 9]
[100 101   2   3   4   5   6   7   8   9]


# Universal functions
- add, substract, multiply, divide, mod, negative, positive, power
- absolute, rint, floor, ceil, trunc, fix
- matmul, dot
- greater, less, greater_equal, less_equal
- maximum, minimum

In [ ]:
a1 = np.arange(1, 10).reshape(3, -3)
a2 = np.full((3, 1), 2)

print(a1)
print(a2)

a3 = np.power(a1, a2)
print(a3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2]
 [2]
 [2]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [ ]:
a1 = np.linspace(-5, 5, 10)
print(a1)

a2 = np.fix(a1) # round toward zero
print(a2)

[-5.         -3.88888889 -2.77777778 -1.66666667 -0.55555556  0.55555556
  1.66666667  2.77777778  3.88888889  5.        ]
[-5. -3. -2. -1. -0.  0.  1.  2.  3.  5.]


In [ ]:
a1 = rng.integers(0, 10, 10)
a2 = rng.integers(0, 10, 10)
print(a1)
print(a2)

print(np.matmul(a1, a2)) # Get product
print(np.greater(a1, a2))
print(np.maximum(a1, a2))

[0 5 7 0 0 4 9 8 5 5]
[0 5 3 3 5 3 6 0 2 7]
157
[False False  True False False  True  True  True  True False]
[0 5 7 3 5 4 9 8 5 7]
