<a href="https://colab.research.google.com/github/Jinwooseol/Numpy-and-Pandas/blob/main/2022_03_21_broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Broadcasting with Numpy
- Good for **time complexity** and **space complexity**
- Optimize time complexity (**Best fit**)

In [ ]:
import numpy as np

In [ ]:
def print_info(obj):
  print('type: ', type(obj))
  print('print: ')
  print(obj)

  print('ndim: ', obj.ndim)
  print('shape: ', obj.shape)
  print('size: ', obj.size)
  print('dtype: ', obj.dtype) # dtype: Data type
  print('itemsize: ', obj.itemsize) # itemsize: Number of bytes that one of element occupied
  print('data: {}'.format(obj.data))  # data: Address of array
  print('-'*20)


# Basic Operations

In [ ]:
a1 = np.arange(10)
print(a1)

# a2 = np.array([3] * 10)
a2 = np.full((10,), 3)    # Memory waste
print(a2)
print(a1 + a2)

# Broadcasting
print(a1 + 3)

a2 = np.array([3])
print(a1 + a2)

print('-'*20)
print(a1)
print(a2)
print(a1 + a2)
print(a1 - a2)
print(a1 * a2)
print(a1 / a2)
print(a1 // a2)
print(a1 % a2)


[0 1 2 3 4 5 6 7 8 9]
[3 3 3 3 3 3 3 3 3 3]
[ 3  4  5  6  7  8  9 10 11 12]
[ 3  4  5  6  7  8  9 10 11 12]
[ 3  4  5  6  7  8  9 10 11 12]
--------------------
[0 1 2 3 4 5 6 7 8 9]
[3]
[ 3  4  5  6  7  8  9 10 11 12]
[-3 -2 -1  0  1  2  3  4  5  6]
[ 0  3  6  9 12 15 18 21 24 27]
[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.        ]
[0 0 0 1 1 1 2 2 2 3]
[0 1 2 0 1 2 0 1 2 0]


# Rules of Broadcasting
- If shape can't apply in **vertical** or **horizontal way**  
  $→$ It can't be broadcasting

In [ ]:
a1 = np.arange(20).reshape(4,5)
a2 = np.full((4,5), 3)
a3 = np.full((5,), 3)   # Broadcasting Positive
a3 = np.full((4,1), 3)  # Broadcasting Positive
a3 = np.full((1,5), 3)  # Broadcasting Positive

a3 = np.full((4,), 3)   # Broadcasting Negative

print(a1)
print(a2)
print(a3)
print(a1 + a2)
print(a1 + a3)
print(a1 + 3)           # Broadcasting Positive

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]
[3 3 3 3 3]
[[ 3  4  5  6  7]
 [ 8  9 10 11 12]
 [13 14 15 16 17]
 [18 19 20 21 22]]
[[ 3  4  5  6  7]
 [ 8  9 10 11 12]
 [13 14 15 16 17]
 [18 19 20 21 22]]
[[ 3  4  5  6  7]
 [ 8  9 10 11 12]
 [13 14 15 16 17]
 [18 19 20 21 22]]


In [ ]:
a1 = np.arange(10, 34).reshape(2,3,4)
print(a1.shape)
print('-'*20)

print('axis 0: \n', a1.sum(axis=0))
print('-'*20)
print('axis 1: \n', a1.sum(axis=1))
print('-'*20)
print('axis 2: \n', a1.sum(axis=2))
print('-'*20)
print('axis 0.shape: ',a1.sum(axis=0).shape)
print('axis 1.shape: ',a1.sum(axis=1).shape)
print('axis 2.shape: ',a1.sum(axis=2).shape)

(2, 3, 4)
--------------------
axis 0: 
 [[32 34 36 38]
 [40 42 44 46]
 [48 50 52 54]]
--------------------
axis 1: 
 [[42 45 48 51]
 [78 81 84 87]]
--------------------
axis 2: 
 [[ 46  62  78]
 [ 94 110 126]]
--------------------
axis 0.shape:  (3, 4)
axis 1.shape:  (2, 4)
axis 2.shape:  (2, 3)


In [ ]:
a1 = np.arange(10, 34).reshape(2,3,4)
a2 = np.arange(100, 340, 10).reshape(2,3,4)


print(a1)
print('-'*20)
print(a2)
print(a1 + a2)

[[[10 11 12 13]
  [14 15 16 17]
  [18 19 20 21]]

 [[22 23 24 25]
  [26 27 28 29]
  [30 31 32 33]]]
--------------------
[[[100 110 120 130]
  [140 150 160 170]
  [180 190 200 210]]

 [[220 230 240 250]
  [260 270 280 290]
  [300 310 320 330]]]
[[[110 121 132 143]
  [154 165 176 187]
  [198 209 220 231]]

 [[242 253 264 275]
  [286 297 308 319]
  [330 341 352 363]]]


In [ ]:
a1 = np.arange(10, 34).reshape(2,3,4)
a2 = np.full((4,), 3)
a3 = np.full((3,4), 3)
a4 = np.full((1,4), 3)
a5 = np.arange(4)

print(a1 + a2)
print('-'*20)
print(a1 + a3)
print('-'*20)
print(a1 + a4)
print('-'*20)
print(a1 + a5)
print('-'*20)
print((a1 + a2) == (a1 + a3))

[[[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]
--------------------
[[[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]
--------------------
[[[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]
--------------------
[[[10 12 14 16]
  [14 16 18 20]
  [18 20 22 24]]

 [[22 24 26 28]
  [26 28 30 32]
  [30 32 34 36]]]
--------------------
[[[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]]


In [ ]:
a1 = np.arange(1,9).reshape(2,-1)
print(a1)
a1[0] += 3  # Selective broadcasting
print(a1)

[[1 2 3 4]
 [5 6 7 8]]
[[4 5 6 7]
 [5 6 7 8]]


#ndarray.all():
- **If all element are True**, then return true, else return false  

#ndarray.any():
- **If there exist True more than one**, then return true, else return false

In [ ]:
a1 = np.arange(10)
a2 = np.arange(0,10,2)
print(a1)
print(a2)

x1 = a1 % 2 == 0
x2 = a2 % 2 == 0
print(x1)
print(x2)

print(x1.all())
print(x2.all())

x3 = a2 % 2 == 1

print(x1.any())
print(x3.any())

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[ True False  True False  True False  True False  True False]
[ True  True  True  True  True]
False
True
True
False


#np.flatten()
- Reshape to 1D array
- Copy and Paste

#np.ravel()
- Reshape to 1D array
- View

In [ ]:
a1 = np.arange(10).reshape(2,-1)

print(a1)

x1 = a1.flatten()
x1[0] = 10
x2 = a1.ravel()
x2[1] = 11

print(x1)   # create new ndarray
print(x2)   # create view (referencing)

print(a1)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[10  1  2  3  4  5  6  7  8  9]
[ 0 11  2  3  4  5  6  7  8  9]
[[ 0 11  2  3  4]
 [ 5  6  7  8  9]]


#argmax, argmin
- Return index of maximum or minimum value in array

In [ ]:
a1 = np.arange(10, 30).reshape(4,5)
print(a1)

print(a1.argmax())  # Return index
print(a1.argmin())  # Return index
print(a1.argmax(axis=0))
print(a1.argmax(axis=1))

# Time complexity?

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
19
0
[3 3 3 3 3]
[4 4 4 4]


TypeError: ignored

In [ ]:
a1 = np.random.rand(10).reshape(2, -1)
print(a1)

print(a1.argmax())
print(a1.argmin())
print(a1.argmax(axis=0))
print(a1.argmax(axis=1))

[[0.50736117 0.54187253 0.92624082 0.93052616 0.59055363]
 [0.4176428  0.32959766 0.34393262 0.47885155 0.9125971 ]]
3
6
[0 0 0 0 1]
[3 4]


# ndarray.argsort()
- Return index array of priority

# ndarray.take( )
- Get index list for sorting and return sorted array
- Copy and paste

# ndarray.sort()
- In-place sorting
- View

In [ ]:
a1 = np.array([10,3,1,5,2,7,9])

index_list = a1.argsort()
print(index_list)

print(a1.take(index_list))
print(a1)

a1.sort()
print(a1)

[2 4 1 3 5 6 0]
[ 1  2  3  5  7  9 10]
[10  3  1  5  2  7  9]
[ 1  2  3  5  7  9 10]


# np.choose(index_list, ndarray)
- From ndarray choose values  
Ex. [2, 3, 1, 0] -> choose [0,2], [1,3], [2,1], [3,1]


In [ ]:
choices = np.arange(100, 116).reshape(4,4)
print(choices)

print('choose: ',np.choose([2,3,1,0], choices))

[[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]
 [112 113 114 115]]
choose:  [108 113 106 103]


#Sum, prod
- Return value of sum or product

# cumsum, cumprod
- Return array of **cumulative** sum, product

In [ ]:
a1 = np.arange(1, 10)
print(a1)
print(a1.sum())
print(a1.cumsum())
print(a1.prod())
print(a1.cumprod())

[1 2 3 4 5 6 7 8 9]
45
[ 1  3  6 10 15 21 28 36 45]
362880
[     1      2      6     24    120    720   5040  40320 362880]


In [ ]:
print(a1)
print(a1.min())
print(a1.max())
print(a1.ptp())   # peak to peak: max - min
print(a1.mean())
print(a1.std())
print(a1.var())


[1 2 3 4 5 6 7 8 9]
1
9
8
5.0
2.581988897471611
6.666666666666667


# Squeeze
- Delect unessary dimention 

#swapaxes
- Swap two axes

# transpose
- Make transpose

In [ ]:
a1 = np.arange(10)
print(a1)

a2 = a1[np.newaxis,:]
print(a2)
print(a2.squeeze())

a2 = a1.reshape(2, -1)
print(a2)
print(a2.swapaxes(0,1))
print(a2.transpose())

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4 5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [ ]:
a1 = np.arange(24).reshape(2,3,4)
print('a1: \n',a1)
print('a1.shape: ',a1.shape)
print('a1.transpose: \n',a1.transpose())
print('a1.transpose.shape: ',a1.transpose().shape)

print('swap: \n',a1.swapaxes(0, 2))
print('swap.shape: ',a1.swapaxes(0,2).shape)

a1: 
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
a1.shape:  (2, 3, 4)
a1.transpose: 
 [[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]
a1.transpose.shape:  (4, 3, 2)
swap: 
 [[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]
swap.shape:  (4, 3, 2)
